name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./front-end

    - name: Build project
      run: npm run build
      working-directory: ./front-end
      env:
        VITE_KAKAO_APP_KEY: ${{ secrets.VITE_KAKAO_APP_KEY }}
        VITE_BE_ENDPOINT: ${{ secrets.VITE_BE_ENDPOINT }}

    - name: Deploy to Vercel
      run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      working-directory: ./front-end
